Registration with google account
RezenkovD/cash-money pull request #1
Opened 2023-02-27 21:12 UTC by RezenkovD

2023-02-27 22:01 UTC, qqlexa requested changes

2023-02-27 22:01 UTC, qqlexa commented on src/services/user.py
> +def get_users(db: Session):
Add return annotation.

2023-02-27 22:01 UTC, qqlexa commented on src/services/user.py
> +def create_user(db: Session, login: str, first_name: str, last_name: str, picture: url):
Add return annotation.

2023-02-27 22:01 UTC, qqlexa commented on src/services/user.py
> +import models
Why not ```python
from models import User
```?

2023-02-28 06:42 UTC, RezenkovD commented on requirements.txt
>  anyio==3.6.2
I agree with you. This should be exclusive to the project.

2023-02-28 06:44 UTC, RezenkovD commented on src/routers/registration.py
> +CONF_URL = "https://accounts.google.com/.well-known/openid-configuration"
Nicely observed

2023-02-28 06:45 UTC, RezenkovD commented on src/routers/registration.py
> +        if db_user:
Thanks. This good idea.

2023-02-28 06:52 UTC, RezenkovD commented on alembic/versions/64da66deb62d_add_user_table.py
> +        sa.Column("picture", sqlalchemy_utils.types.url.URLType(), nullable=False),
-

2023-02-28 10:03 UTC, qqlexa requested changes

2023-02-28 10:03 UTC, qqlexa commented on src/routers/registration.py
> +    return await oauth.google.authorize_redirect(request, redirect_uri)
Let's create tests

2023-03-03 10:54 UTC, qqlexa requested changes

2023-03-03 10:54 UTC, qqlexa commented on src/routers/registration.py
> +        create_user(
Can we catch it from the func and later return it? db_user = create_user()

2023-03-03 10:54 UTC, qqlexa commented on src/routers/registration.py
> +    return get_user(db, login=user["email"])
return db_user?

2023-03-03 10:54 UTC, qqlexa commented on src/services/user.py
> +def get_users(db: Session) -> List[Type[schemas.User]]:
It is not `List[Type[schemas.User]]` here. It is `List[models.User]:`
By the way, what is the version of your python? It is available to use list[] from python3.9

2023-03-03 10:54 UTC, qqlexa commented on src/services/user.py
> +def create_user(db: Session, login: str, first_name: str, last_name: str, picture: url) -> schemas.User:
It is not `schemas.User` it is `models.User`

2023-03-03 11:25 UTC, RezenkovD commented on src/config.py
> +    TEST_SQLALCHEMY_DATABASE_URI: str
I agree about the TEST. But if you use one variable for DB. Your main database crashes every time after unit testing.

2023-03-03 11:26 UTC, RezenkovD commented on src/models/user.py
> +    picture = Column(URLType, unique=True, nullable=True)
Exactly. After all, the picture is taken from a Google account. But you can not include it.

2023-03-03 11:27 UTC, RezenkovD commented on src/routers/registration.py
> +        create_user(
This good idea. Thanks.

2023-03-03 11:27 UTC, RezenkovD commented on src/routers/registration.py
> +    return get_user(db, login=user["email"])
Exclusively for testing.

2023-03-03 11:28 UTC, RezenkovD commented on src/services/user.py
> +def get_users(db: Session) -> List[Type[schemas.User]]:
3.10 :)

2023-03-03 11:29 UTC, RezenkovD commented on src/services/user.py
> +def create_user(db: Session, login: str, first_name: str, last_name: str, picture: url) -> schemas.User:
Oh. Exactly. Thank you

2023-03-03 12:43 UTC, RezenkovD commented on src/config.py
> +    TEST_SQLALCHEMY_DATABASE_URI: str
So. I understand you. There should be only one var.

2023-03-03 16:28 UTC, qqlexa requested changes

2023-03-03 16:28 UTC, qqlexa commented on src/services/user.py
> +def get_user(db: Session, login: str) -> Union[User, None]:
Union[User, None] = Optional[User]

2023-03-03 16:28 UTC, qqlexa commented on src/services/user.py
> +def create_user(db: Session, login: str, first_name: str, last_name: str, picture: url) -> User:
We use it once. Let's move into the router.

2023-03-06 09:17 UTC, merged