user-replenishments
RezenkovD/cash-money pull request #14
Opened 2023-04-11 08:57 UTC by RezenkovD

2023-04-11 16:29 UTC, qqlexa requested changes

2023-04-11 16:29 UTC, qqlexa commented on .gitignore
> +.vscode/settings.json
What about whole folder `.vscode/`?

2023-04-11 16:29 UTC, qqlexa commented on src/models/status.py
Is it model status? I guess it can be moved to enum folder

2023-04-11 16:29 UTC, qqlexa commented on src/routers/replenishment.py
> +@router.get("/all-time/", response_model=List[UserReplenishment])
`read_replenishments_all_time`, `read_replenishments_month` and `read_replenishments_time_range` have the same logic. Use query_params and only one route

2023-04-12 06:28 UTC, RezenkovD commented on src/routers/replenishment.py
> +@router.get("/all-time/", response_model=List[UserReplenishment])
Thanks. This very good idea

2023-04-12 17:26 UTC, qqlexa approved these changes

2023-04-12 17:35 UTC, merged